### PR TITLE
Removing Dependencies on Helper Functions

### PR DESCRIPTION
**Pull request by awjudd**
Fixing #356 #355

### CODE REVIEW

**Comment by awjudd** [comment]
Also #358

**Comment by awjudd** [comment]
For those of you who this blocks the upgrade to Laravel 6, you are able to temporarily change your `composer.json` file to the following:
In the "require" section:
```
"venturecraft/revisionable": "dev-bug/array-get#21e4b1ad17dc6d73d8370cc02f17b7ed18297d4e",
```

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/awjudd/revisionable"
        }
    ],
```

**Comment by ethanransdellrarebird** [comment]
@duellsy can this be merged?

**Comment by ethanransdellrarebird** [comment]
Can this be moved into a release?

**Comment by duellsy** [comment]
Yup, all done. v1.32.0

**Pull request merged**
