### PR TITLE
Fix for laravel backpack not saving user id

### PR DESCRIPTION
**Pull request by dilneiss**
With this fix it is still not working: https://github.com/VentureCraft/revisionable/pull/377

So i updated and tested and now is saving user id

### CODE REVIEW

**Comment by dilneiss** [comment]
someone can approve this?

**Comment by dilneiss** [comment]
is this project still active?

**Comment by duellsy** [comment]
Apologies for not closing this off, however this was made available in 1.35.0

**Comment by Reinbier** [comment]
Hi,

When using Laravel Backpack (and thus ```backpack_auth()```) in combination with this project, the user Id still doesn't get inserted correctly in the database. I use the RevisionableTrait in combination with the package 'backpack/revise-operation'.

Digging deeper inside your code I discovered the fix mentioned in [https://github.com/VentureCraft/revisionable/pull/377](#377) was only added to the Revisionable.php class, and not in the RevisionableTrait, thus leaving user Id set to NULL in the revisions table.

I implemented the following temporary fix, using a custom Trait to inherit your trait and overwrite the getSystemUserId() method:
```
/**
 * Class RevisionableTrait extends that of Venturecraft\Revisionable
 */
trait MyRevisionableTrait
{
    use \Venturecraft\Revisionable\RevisionableTrait;

    /**
     * Attempt to find the user id of the currently logged in user
     * Supports Cartalyst Sentry/Sentinel based authentication, as well as stock Auth
     **/
    public function getSystemUserId()
    {
        try {
            if (class_exists($class = '\Cartalyst\Sentry\Facades\Laravel\Sentry')
                    || class_exists($class = '\Cartalyst\Sentinel\Laravel\Facades\Sentinel')) {
                return ($class::check()) ? $class::getUser()->id : null;
            } elseif (function_exists('backpack_auth') && backpack_auth()->check()) {
                return backpack_user()->id;
            } elseif (\Auth::check()) {
                return \Auth::user()->getAuthIdentifier();
            }
        } catch (\Exception $e) {
            return null;
        }

        return null;
    }
}
```

Here the code works correct! I just copied the code from the Revisionable-class that you already updated :-) 

I hereby want to kindly ask you to implement this fix in your project.

Kind regards

**Comment by duellsy** [comment]
Good catch, would you mind submitting a fresh PR to bring it to the trait?

**Comment by Reinbier** [comment]
I just made a pull request, @duellsy. I also just discovered @dilneiss was referencing the same fix, lol!

**Pull request closed without merging**
