### PR TITLE
Add ip column

### PR DESCRIPTION
**Pull request by yhbyun**
How about logging ip address ?

### CODE REVIEW

**Comment by astierler** [comment]
@yhbyun - this isn't compatible with Laravel 4.x. (no ``request()`` function). If you can modify this to support both platforms it can be added in - otherwise this functionality will most likely make it into the future 5.x branch

**Comment by vzool** [comment]
@astierler  no need to use `request()` we still have a legacy one `$_SERVER["REMOTE_ADDR"]`.
This is what I did in my last **Pull Request** #258.
Hope you like it ... Thanks

**Comment by VeeeneX** [comment]
@vzool It's not good idea to store IP

**Comment by vzool** [comment]
@VeeeneX Why that? ^_^

**Pull request closed without merging**
