### PR TITLE
Added Revision Cleanup to remove old revisions.

### PR DESCRIPTION
**Pull request by sniper7kills**
As per #152; this is untested.

### CODE REVIEW

**Comment by rajivseelam** [comment]
Any idea on when this might me merged?

**Comment by duellsy** [comment]
Just need someone to add some documentation on it in the readme, I'm just slammed with work at the moment otherwise I'd do it myself.

**Comment by rajivseelam** [comment]
That someone can be anyone? As in I can send a pull request?

**Comment by duellsy** [comment]
Definitely

**Comment by duellsy** [comment]
Also, @rajivseelam & @sniper7kills please do all pull requests on the `develop` branch (closing this PR for now)

**Comment by duellsy** [comment]
Merged with PR 156  https://github.com/VentureCraft/revisionable/pull/156

**Pull request closed without merging**
