### PR TITLE
add Laravel 10 support

### PR DESCRIPTION
**Pull request by pxpm**

### CODE REVIEW

**Comment by tabacitu** [comment]
Thanks Pedro! It was that easy, huh?

**Comment by pxpm** [comment]
Hey guys, i've also updated dev dependencies. 

There were some issues with tests, I fixed two of them. 
The return type of the `setUp` method and the database name. 
The change on return type may be a breaking change, so it's probably better to tag a new version with only l10+ support with PHPUnit 9.5+ ? 

Tests are now running and green, but we still have some issues with PHPUnit xml file. 
I think the invalid attributes are just disregarded so the tests run fine:
#### Using PHPUnit 10.x
image

#### Using PHPUnit 9.6x
image

I also tested revisionable on our use case, it seems to be working fine:
image

Cheers

**Comment by duellsy** [comment]
Laravel 10 support merged in with #420

**Comment by niladam** [comment]
@duellsy thank you! @pxpm thank you too!

**Pull request closed without merging**
