### PR TITLE
support MorphMap

### PR DESCRIPTION
**Pull request by xVismutx**
support MorphMap

### CODE REVIEW

**Comment by synthor** [comment]
@duellsy Could you please merge this PR or is this project dead?

**Comment by duellsy** [comment]
Looks good, however I'm unsure if this is supported in Laravel 4, so would be a breaking change if merged.

**Comment by pestopancake** [comment]
For anyone looking for a quick fix, this worked for me; https://gist.github.com/pestopancake/6e86b31732596032a5695933adfb1047

**Comment by duellsy** [comment]
merged in #269

**Pull request closed without merging**
