### PR TITLE
Added action to determine type of revision & Much More

### PR DESCRIPTION
**Pull request by mysteryos**
1) Changed model events in RevisionableTrait.php and Revisionable.php
2) Added column 'action' to migration file.
3) Added 'action' field to revision to determine type of revision. Type of revisions include: 
- CREATE (i.e sql INSERT table row)
- INSERT(i.e sql UPDATE table column - from old null value to new non-null value)
- UPDATE (i.e sql UPDATE table from old non-null value to new non-null value)
- DELETE (i.e sql UPDATE table column from old non-null value to new null value)
- REMOVE (i.e sql DELETE table row)

4) Set $saveCreateRevision attribute in eloquent model to save revisions with action 'CREATE' when set to TRUE.

5) Set $revisionClassName attribute in eloquent model to provide human-readable name for Eloquent models.

6) Removed attribute 'updating' since we are now using 'updating' model events to determine when a model is being updated.

Todo:

1) Provide pre-formatted string for getRevisionString()
2) Provide a way to merge revisions of revisionable model and its relationships (which are revisionable as well).

### CODE REVIEW

**Comment by stevebauman** [comment]
This is great! Definitely looking forward to this pull.

**Comment by Omranic** [comment]
@duellsy Any updates on v2 & the #102 merge to the core package?

**Comment by Omranic** [comment]
@mysteryos Is this pull request compatible with Laravel 5?

**Comment by carlosviol** [comment]
@mysteryos Let me help you with something?

**Comment by mysteryos** [comment]
Hey, i have a fork lying around in my repository that contains all the latest updates merged. You can use that. Or, use https://github.com/jarektkaczyk/revisionable. Code base is PSR compliant and maintained.

**Comment by carlosviol** [comment]
Cool, thanks man!

**Comment by carlosviol** [comment]
@mysteryos I've checked and it works just in Laravel 5. Here we use 4.2, unfortunately :(

I started with PHP & Laravel recently and I preferred the Sofa approach with raw data changes, but maybe I will do a fork of the VentureCraft with a merge of your old fork and the recent changes here. What do you think about?

**Comment by astierler** [comment]
I like + agree with many of the features, and have done similar versions in my custom implementations on larger apps. Will look into implementing these in upcoming versions, either supporting backward compatibility - or a 5.x+ branch going forward.

**Pull request closed without merging**
