### PR TITLE
Added functionality to track model creations

### PR DESCRIPTION
**Pull request by argia-andreas**
Ability to also track model creations in revisions.

It can be displayed like this:
```
@foreach($user->revisionHistory as $history)
  @if($history->key == 'created_at' && !$history->old_value)
    <li>Resource was created at {{ $history->new_value }}</li>
  @else
    <li>{{ ucfirst($history->key) }} changed from {{ $history->old_value }} to {{ $history->new_value }}</li>
  @endif
@endforeach
```

### CODE REVIEW

**Comment by argia-andreas** [comment]
@fobus42 added this as a request. I just put it together as a pull request.

**Comment by duellsy** [comment]
If you're able to wrap this in a per model config to enable storing creates, with it disabled by default, I'll be happy to merge.

Reason being, there's a lot of sites already using this, and if we were to merge this commit in they'll all start getting new records for all the creates. There shouldn't be any effect on existing users of revisionable after this PR is merged.

**Comment by argia-andreas** [comment]
@duellsy Great! Didn't think about that.
I'll give it a go and get back to you.

**Comment by argia-andreas** [comment]
Hello @duellsy 

Please see the changes I made.

I added a conditional check that requires `protected $revisionCreationsEnabled = true;` to be set in the model, otherwise it wont store the revision.
I also added it to the documentation.
I tried to follow the style in the docs and code as well as I could.

I'm new to making pull requests, so if you want any change just let me know.

Will these changes do?

Great package by the way!

**Comment by argia-andreas** [comment]
@duellsy Sorry for disturbing you about this again.

Is this pull request OK for you now?

Or do you want me to change anything about it?
Just let me know if you want me to change anything and I'll do my best to do it the way you want.

It would be nice to have this functionality in the package as I will use it in a app I'm building :-)

**Comment by mmodler** [comment]
Merge?

**Comment by duellsy** [comment]
Apologies for the delay on merging this, gang. Had some local issues.

**Comment by argia-andreas** [comment]
@duellsy No worries, thank you! And thanks again for this package! :-)

**Pull request merged**
