### PR TITLE
Enable to choose db connection

### PR DESCRIPTION
**Pull request by verox**
Enable to choose db connection by creating simple config file:
`config/revisionable.php`

For example:

`
return [
    'db_connection' => 'mysql-revision'
];`

### CODE REVIEW

**Comment by emielmolenaar** [comment]
Wouldn't it be more awesome to just use the connection of the model that is being stored? Something like

`DB::connection($this->getConnectionName())->table($$revision->getTable())->doStuff()`

?

**Comment by antoniopaisfernandes** [comment]
I agree with @emielmolenaar approach. We have an app that has model fetched from different connections and the revisions should be stored also on those connections 'revisions' table.

**Comment by lephleg** [comment]
I've tried implementing this on my local as a workaround. Because of the trait approach Revisionable is using, you cannot override the `$connection` property only for revisions as it should also apply for your base model.

```
Illuminate\Database\Eloquent\Model and Venturecraft\Revisionable\RevisionableTrait define the same property ($connection) in the composition of Report. However, the definition differs and is considered incompatible.
```

Have you found a solution to this?

**Comment by ragingdave** [comment]
Is there any progress on getting this merged? Also as a side note, although for the most part I agree with @emielmolenaar about having the revisions stored in the same connection as the model being manipulated, there are certainly instances where storing them separately is required (like my case now). The default should be the same connection but with the option to not use the same connection.

**Comment by fridzema** [comment]
is there any progress in 2018 on this?

**Comment by emielmolenaar** [comment]
[Unfortunately, I guess not ...](https://github.com/VentureCraft/revisionable/commit/60c26dd6ad157b6973129ef3579748d32bff7fca)

**Comment by emielmolenaar** [comment]
Yep. I still use it in some apps, works perfectly fine. I have failed to find a nice alternative, so any suggestions are welcome!

**Comment by ragingdave** [comment]
@emielmolenaar I actually use this package in one of my applications but I will be transitioning to the spatie/laravel-activitylog. Pretty much any spatie package has been my goto for pretty much anything.

**Comment by duellsy** [comment]
Incredibly late (understatement of the decade) response to this, but what would be the most preferred path here?

Using `$this->getConnectionName()` seemed like a good option, but there's also folks preferring for that not to be the default.

I'm going to close this particular PR, but if someone has a newer solution and can make a new PR on the current branch I'll happily merge in

**Pull request closed without merging**
